version: '3'

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: '${PROJECT_NAME}-nginx'
    tty: true
    ports:
      - 80:80
    volumes:
      - './nginx/conf_d:/etc/nginx/conf.d'
    environment:
      TZ: 'Asia/Tokyo'

